name: ChopChop
options:
  bundleIdPrefix: com.seowalex
  xcodeVersion: "12.3"
  deploymentTarget:
    iOS: 14.3
  groupSortPosition: top
packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 5.6.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 7.9.1
  CombineFirebase:
    url: https://github.com/rever-ai/CombineFirebase
    branch: 02bc159531795b98bf7ff83dfe8c794cf805945e
targets:
  ChopChop:
    type: application
    platform: iOS
    sources: ChopChop
    dependencies:
      - package: GRDB
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: CombineFirebase
    preBuildScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint autocorrect && swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  ChopChopTests:
    type: bundle.unit-test
    platform: iOS
    sources: ChopChopTests
    dependencies:
      - target: ChopChop
